apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testresources.example.com
spec:
  group: example.com
  names:
    plural: testresources
    singular: testresource
    kind: TestResource
    shortNames:
    - tr
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                message:
                  type: string
                  description: A message for testing purposes.
                replicas:
                  type: integer
                  description: The number of desired replicas.
                  minimum: 1
                  maximum: 10
